### ISSUE TITLE
Create: refactor

### ISSUE THREAD

**Issue by 0xGabi** [aragon/govern#175]
This issue aim to use hardhat advance functionalities:

- [ ] Move to typescript

- [ ] Add helpers to abstract task creation

- [ ] Migrate to hardhat

**Comment by onbjerg** [comment]
Any way we could also get network support for networks that are not mainnet or Rinkeby? It would make it easier to deploy Govern on xDai for instance :angel:
