### ISSUE TITLE
Epic: Implement API MVP

### ISSUE THREAD

**Issue by izqui** [aragon/govern#41]
### Abstract

API server to host at api.aragon.org or api.[govern app domain]. The Aragon Connect equivalent for Govern should hit the api instead of a subgraph directly

### Why

- DX is incredibly important for our product's success. Aragon Connect changed Aragon forever.
- Aragon Connect is great, but having a more web2-like API is going to make it easier for non-crypto devs
- API will allow us to monitor real use of our tools to detect usage patterns

### Deliverables

MVP deliverables by priority:
- Passthrough proxy to subgraph. Perform GraphQL queries directly to our host allowing us to hot swap the Graph node being used.
- Basic JSON views (`/daos`, `/daos/[dao]/queue`, etc)
- Basic API docs using something like https://swagger.io/resources/open-api/

Future features:
- Create DAOs, schedule, challenge and execute actions via API (API pays for gas)
- Register webhooks (eg. on DAO schedule send POST to `dao.org/webhook`)

### Acceptance criteria

- Once first feature is done, we can deploy and continue evolving
- API is deployed on master pushes from CD on Github Actions
- API is monitored for errors
- API should be relatively easy to deploy for people to host mirrors (stop tradeoffs between great DX and decentralization)

### Involved persons

- Owner: @bpierre 
- Design: @bpierre + @izqui 
- Implementation: @bpierre + @promaty
- Review: @promaty + @0xGabi 
- QA: @Evalir + @izqui 
- Documentation: @bpierre 
- Ops: @promaty 

### Inspiration

- https://0x.org/docs/api (crypto api)
- https://developer.github.com/v3/ (rest + graphql)
- https://reactjs.org/docs/getting-started.html (great docs)

### Phases

- [ ] [Phase 1](https://github.com/aragon/govern/issues/46)
- [ ] [Phase 2](https://github.com/aragon/govern/issues/47)
- [ ] [Phase 3](https://github.com/aragon/govern/issues/48)
- [ ] [Phase 4](https://github.com/aragon/govern/issues/49)
